### SJS 2/13/14. Find HRH's. ###

#$ -N blast
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-4:1


source ~/.bashrc

# Create Working Directory and remove anything that might have been there woops!
MYJOB=$JOB_NAME-$JOB_ID-$SGE_TASK_ID
WDIR=/state/partition1/sjs3495/$MYJOB

mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR

pwd

# Copy Data and Config Files
cp /home/sjs3495/AmineReceptors/scripts/run_blast.py .

module load python
BLASTDB=$BLASTDB:/share/WilkeLab/work/sjs3495/nr
export BLASTDB
python run_blast.py $SGE_TASK_ID

RDIR=/home/sjs3495/AmineData/$MYJOB
mkdir -p $RDIR

# Cleanup
cp seed* $RDIR
cp final* $RDIR
rm -rf $WDIR
