### SJS 2/13/14. ###

#$ -N amineblast
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-42:1  #4 for h4h, 42 for amine


source ~/.bashrc

# Create Working Directory and remove anything that might have been there woops!
MYJOB=$JOB_NAME-$JOB_ID-$SGE_TASK_ID
WDIR=/state/partition1/sjs3495/$MYJOB
RDIR=/home/sjs3495/Blast/$MYJOB

mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR

# Copy and run
cp /home/sjs3495/AmineReceptors/scripts/blast/run_blast.py .
module load python
BLASTDB=$BLASTDB:/share/WilkeLab/work/sjs3495/nr
export BLASTDB
python run_blast.py $SGE_TASK_ID


# Save and Cleanup
mkdir -p $RDIR
cp blast_ids* $RDIR
rm -rf $WDIR
