#### SJS. Submit bootstrap to cluster. ####

#!/bin/bash
#$ -N bootstrap
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1
#$ -pe serial 16

source ~/.bashrc

# Set up directories
RDIR=/home/sjs3495/$JOB_NAME
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $RDIR
mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi

cd $WDIR

# Copy data and python files
cp /home/sjs3595/amine_aa_final.aln .
cp /home/sjs3495/AmineReceptors/scripts/bootstrap.py .
cp /home/sjs3495/bin/FastTreeMP .

# Run bootstrap
module load python
python bootstrap.py amine_aa_final.aln protein 1  # alnfile, datatype, number bootstraps to run
# Save the output files
cp bootaln.txt $RDIR/bootaln$SGE_TASK_ID.txt 
cp boottree.txt $RDIR/boottree$SGE_TASK_ID.txt 

# Cleanup
rm -rf $WDIR
