#### SJS. Submit bootstrap to cluster. ####

#!/bin/bash
#$ -N bootamine
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1
#$ -pe serial 16

source ~/.bashrc

# Set up directories
RDIR=/home/sjs3495/$JOB_NAME-$JOB_ID
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $RDIR
mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi

cd $WDIR

# Copy data and python files
cp /home/sjs3495/amine_aa_final.aln aln.fasta
cp /home/sjs3495/AmineReceptors/scripts/bootstrap/bootstrap_echadechad.py .
cp /home/sjs3495/bin/FastTreeMP .

# Run bootstrap
module load python
python bootstrap_echadechad.py aln.fasta protein  # alnfile, datatype. this script runs 1 at a time 
# Save the output files
cp bootaln.txt $RDIR/bootaln$SGE_TASK_ID.txt 
cp boottree.txt $RDIR/boottree$SGE_TASK_ID.txt 

# Cleanup
rm -rf $WDIR
